languageCode = "en-us"
title = "Kesugi Ridge Traverse"
baseURL = "http://kesugiridgetraverse.com/"

[params]
  logo = "/img/kesugi-logo.png"
  email = "matiasmountain@gmail.com"
  phone = "907-529-4178"
